require("dotenv").config({ path: require("path").resolve(__dirname, "../.env") });
const mongoose = require("mongoose");
const Product = require("../model/Product");

const SEED_JERSEYS = [
  {
    code: "01/FCB",
    name: "FC BARCELONA 125TH ANNIVERSARY",
    season: "24/25 HOME MATCH SPEC",
    club: "FC BARCELONA",
    price: "$125.00",
    priceNumeric: 125,
    imageSrc: "/images/barca-jersey.svg",
    edition: "HERITAGE VAULT EDITION",
    category: "club",
    league: "La Liga",
    sizesAvailable: ["S", "M", "L", "XL"],
    stock: 30,
    rating: 4.9,
    inStock: true,
    showOnLanding: true,
    landingOrder: 0,
    showInShop: true,
    featured: true,
    description: "Commemorative 125th anniversary home kit featuring authentic Blaugrana halved colorway with centenary gold embroidery.",
  },
  {
    code: "02/RMA",
    name: "REAL MADRID CF CHAMARTÍN WHITE",
    season: "24/25 HOME MATCH SPEC",
    club: "REAL MADRID CF",
    price: "$130.00",
    priceNumeric: 130,
    imageSrc: "/images/real-jersey.svg",
    edition: "ROYAL VAULT EDITION",
    category: "club",
    league: "La Liga",
    sizesAvailable: ["M", "L", "XL", "XXL"],
    stock: 25,
    rating: 4.8,
    inStock: true,
    showOnLanding: true,
    landingOrder: 1,
    showInShop: true,
    featured: false,
    description: "Classic Blanco edition with houndstooth micro-jacquard texture and high-density heat-applied crest.",
  },
  {
    code: "03/ARS",
    name: "ARSENAL FC CANNON THIRD SPEC",
    season: "24/25 THIRD MATCH SPEC",
    club: "ARSENAL FC",
    price: "$120.00",
    priceNumeric: 120,
    imageSrc: "/images/arsenal-jersey.svg",
    edition: "GUNNERS ARCHIVE EDITION",
    category: "club",
    league: "Premier League",
    sizesAvailable: ["S", "M", "L", "XL"],
    stock: 20,
    rating: 4.9,
    inStock: true,
    showOnLanding: true,
    landingOrder: 2,
    showInShop: true,
    featured: true,
    description: "Retro trefoil logo paired with standalone cannon crest on celestial lilac base.",
  },
  {
    code: "04/MUFC",
    name: "MANCHESTER UNITED DEVIL SPEC",
    season: "24/25 HOME MATCH SPEC",
    club: "MANCHESTER UNITED",
    price: "$125.00",
    priceNumeric: 125,
    imageSrc: "/images/manchester-united-jersey.svg",
    edition: "RED DEVIL ARCHIVE",
    category: "club",
    league: "Premier League",
    sizesAvailable: ["S", "M", "L", "XL", "XXL"],
    stock: 35,
    rating: 4.7,
    inStock: true,
    showOnLanding: true,
    landingOrder: 3,
    showInShop: true,
    featured: false,
    description: "High-contrast two-tone red gradient designed under Old Trafford floodlight specifications.",
  },
  {
    code: "05/MUFC-TREBLE",
    name: "MAN UTD 98/99 TREBLE WINNERS",
    season: "98/99 VINTAGE FINAL SPEC",
    club: "MANCHESTER UNITED",
    price: "$165.00",
    priceNumeric: 165,
    imageSrc: "/images/manchester-united-jersey.svg",
    edition: "HERITAGE VAULT EDITION",
    category: "vintage",
    league: "Vintage Archive",
    sizesAvailable: ["M", "L", "XL"],
    stock: 12,
    rating: 5.0,
    inStock: true,
    showOnLanding: false,
    landingOrder: 4,
    showInShop: true,
    featured: true,
    description: "Authentic Camp Nou UEFA Champions League final specification with gold star crest.",
  },
  {
    code: "06/ARS-0304",
    name: "ARSENAL 03/04 THE INVINCIBLES",
    season: "03/04 COMMEMORATIVE SPEC",
    club: "ARSENAL FC",
    price: "$150.00",
    priceNumeric: 150,
    imageSrc: "/images/arsenal-jersey.svg",
    edition: "HERITAGE MATCH RUN",
    category: "retro",
    league: "Vintage Archive",
    sizesAvailable: ["S", "M", "L", "XL"],
    stock: 15,
    rating: 4.9,
    inStock: true,
    showOnLanding: false,
    landingOrder: 5,
    showInShop: true,
    featured: false,
    description: "Unbeaten 38-game championship season commemorative issue with gold Premier League sleeve patches.",
  },
  {
    code: "07/ACM-UCL",
    name: "AC MILAN 06/07 ATHENS UCL FINAL",
    season: "06/07 FINALIST MATCH SPEC",
    club: "AC MILAN",
    price: "$155.00",
    priceNumeric: 155,
    imageSrc: "/images/barca-jersey.svg",
    edition: "ROUGE & NOIR ARCHIVE",
    category: "vintage",
    league: "Serie A",
    sizesAvailable: ["S", "M", "L", "XL"],
    stock: 10,
    rating: 4.9,
    inStock: true,
    showOnLanding: false,
    landingOrder: 6,
    showInShop: true,
    featured: false,
    description: "Iconic Athens rematch winner specification featuring Inzaghi final embroidery.",
  },
  {
    code: "08/INT-TREBLE",
    name: "INTER MILAN 09/10 HISTORIC TREBLE",
    season: "09/10 BERNABÉU WINNER SPEC",
    club: "INTER MILAN",
    price: "$145.00",
    priceNumeric: 145,
    imageSrc: "/images/real-jersey.svg",
    edition: "NERAZZURRI COMMEMORATIVE",
    category: "vintage",
    league: "Serie A",
    sizesAvailable: ["M", "L", "XL"],
    stock: 14,
    rating: 5.0,
    inStock: true,
    showOnLanding: false,
    landingOrder: 7,
    showInShop: true,
    featured: false,
    description: "Historic treble triumph edition with Italian tricolore cockade and Coppa Italia insignia.",
  },
  {
    code: "09/RMA-0203",
    name: "REAL MADRID 02/03 CENTENARIO",
    season: "02/03 100TH CENTURY EDITION",
    club: "REAL MADRID CF",
    price: "$160.00",
    priceNumeric: 160,
    imageSrc: "/images/real-jersey.svg",
    edition: "BLANCO HERITAGE RUN",
    category: "retro",
    league: "La Liga",
    sizesAvailable: ["S", "M", "L", "XL", "XXL"],
    stock: 18,
    rating: 4.9,
    inStock: true,
    showOnLanding: false,
    landingOrder: 8,
    showInShop: true,
    featured: false,
    description: "Sponsorless centenary shirt worn during the Zidane, Ronaldo, Figo Galácticos era.",
  },
  {
    code: "10/FCB-0809",
    name: "FC BARCELONA 08/09 SEXTUPLE",
    season: "08/09 HISTORIC ROME RUN",
    club: "FC BARCELONA",
    price: "$155.00",
    priceNumeric: 155,
    imageSrc: "/images/barca-jersey.svg",
    edition: "BLAUGRANA IMMORTAL",
    category: "retro",
    league: "La Liga",
    sizesAvailable: ["S", "M", "L", "XL"],
    stock: 16,
    rating: 5.0,
    inStock: true,
    showOnLanding: false,
    landingOrder: 9,
    showInShop: true,
    featured: false,
    description: "Pep Guardiola historic sextuple victory specification with Rome UCL final patch.",
  },
  {
    code: "11/ARS-9193",
    name: "ARSENAL 91/93 BRUISED BANANA",
    season: "91/93 ICONIC AWAY RUN",
    club: "ARSENAL FC",
    price: "$175.00",
    priceNumeric: 175,
    imageSrc: "/images/arsenal-jersey.svg",
    edition: "CULT RETRO DROP",
    category: "vintage",
    league: "Vintage Archive",
    sizesAvailable: ["M", "L", "XL"],
    stock: 8,
    rating: 4.9,
    inStock: true,
    showOnLanding: false,
    landingOrder: 10,
    showInShop: true,
    featured: false,
    description: "Cult chevron zigzag away graphic regarded as one of the greatest vintage football shirts of all time.",
  },
  {
    code: "12/MUFC-CANTONA",
    name: "MAN UTD 94/96 CANTONA COLLAR",
    season: "94/96 OLD TRAFFORD SPEC",
    club: "MANCHESTER UNITED",
    price: "$170.00",
    priceNumeric: 170,
    imageSrc: "/images/manchester-united-jersey.svg",
    edition: "KING ARCHIVE SPEC",
    club: "MANCHESTER UNITED",
    category: "vintage",
    league: "Vintage Archive",
    sizesAvailable: ["S", "M", "L", "XL"],
    stock: 10,
    rating: 5.0,
    inStock: true,
    showOnLanding: false,
    landingOrder: 11,
    showInShop: true,
    featured: false,
    description: "Black and gold lace-up collar kit made iconic by King Eric Cantona.",
  },
];

async function seedDatabase() {
  const uri = process.env.MONGODB_URI || process.env.MONGO_URI;
  if (!uri) {
    console.error("No MONGODB_URI found in environment");
    process.exit(1);
  }

  console.log("Connecting to MongoDB Atlas...");
  await mongoose.connect(uri);
  console.log("Connected successfully!");

  console.log("Seeding products into 'TheJerseyHub' database...");
  for (const item of SEED_JERSEYS) {
    await Product.findOneAndUpdate(
      { code: item.code },
      { $set: item },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`✓ Seeded/Updated: [${item.code}] ${item.name}`);
  }

  const count = await Product.countDocuments();
  console.log(`\n🎉 Total jerseys in MongoDB database: ${count}`);

  const landingCount = await Product.countDocuments({ showOnLanding: true });
  console.log(`🚀 Active 3D Landing Page Carousel Kits: ${landingCount}`);

  await mongoose.disconnect();
  console.log("Database disconnected cleanly.");
}

seedDatabase().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
